version: "3.8"

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./energy.db
    volumes:
      - .:/code
    working_dir: /code

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173" # Vite dev server
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:8000
    volumes:
      - ./frontend:/app 
      - /app/node_modules
